name: flutter_alert
description: Flutter package which shows a crossplatform alert messages on Android (Material) and iOS (Cupertino).
version: 0.4.0
author: Christoph Jerolimov <jerolimov+flutter@gmail.com>
homepage: https://github.com/jerolimov/flutter_alert

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
